#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gmelisan <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/12/17 11:16:11 by gmelisan          #+#    #+#              #
#    Updated: 2018/12/17 11:16:25 by gmelisan         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = btree_test
FLAGS = -Wall -Wextra -Werror -g

all: $(NAME)

$(NAME):
	gcc $(FLAGS) *.c -o $(NAME)

fclean:
	rm -f $(NAME)
re: fclean all

